name: cci
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - geopandas
  - scipy
  - xarray
  - netcdf4
  - h5py
  - matplotlib
  - seaborn
  - rasterio
  - cartopy
  - geos
  - proj
  - pyproj
  - shapely
  - pyshp
  - dask
  - openpyxl
  - boto3
  - paramiko